# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [3]:
print(A.ndim)
print(A.shape) 
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
print(B - C)
print(B * C)
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(np.exp(B))
print(B.min()) 
print(B.min(axis=1)) 
print(B.min(axis=0))
print(np.argmin(B))
print(np.argmin(B, axis=1))
print(B.sum())
print(B.mean(axis=0))
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:** Selecting a subset of the array. In this case index 1, the entire 2:nd row.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [10]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [12]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [62]:
# a is an 1 dimensional array with 30 elements (0 - 29).
# b is a reshaped 3 dimensional array (2, 3, 5), 2 blocks, 3 rows and 5 elements.
# -1 tells Numpy to automatically calculate the size of the axis.

a = np.arange(30) 
b = a.reshape((2, 3, -1))  

print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [14]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [15]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [16]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [19]:
def add_mult_matrices(mx1, mx2, operation):

    if(isinstance(mx1, np.ndarray) and (isinstance(mx2, np.ndarray))) is False:
        return 'Both inputs must be of type numpy.ndarray'

    if (operation == 'add' or operation == 'multiply') != True:
        return "Choose either 'add' or 'multiply'"

    if operation == 'add':
        if mx1.shape != mx2.shape: 
            return 'Must have the same size for addition'
        else:
            return (mx1 + mx2)
        
    elif operation == 'multiply':
        if (mx1.shape[1] != mx2.shape[0]):
            return "Number of columns in mx1 must match number of rows in mx2 for multiplication"
        else:
            return (mx1 @ mx2)  
        

In [20]:
#Test A
mx1 = np.array([[1, 2], [3, 4]])
mx2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(add_mult_matrices(mx1, mx2, 'add')) 
print(add_mult_matrices(mx1, mx2, 'multiply'))

Must have the same size for addition
Number of columns in mx1 must match number of rows in mx2 for multiplication


In [63]:
#Test B
mx1 = np.array([[1, 2], [3, 4]])
mx2 = np.array([[6, 7], [8, 9]])

print(add_mult_matrices(mx1, mx2, 'add')) 
print(add_mult_matrices(mx1, mx2, 'multiply'))

[[ 7  9]
 [11 13]]
[[22 25]
 [50 57]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

10.1.1<br/> 
Definiera vektorn X = (4, 3)



In [22]:
x = np.array([[4, 3]])
x.shape

(1, 2)

In [64]:
result = 5 * x
result

array([[20, 15]])

In [24]:
result = 3 * x
result

array([[12,  9]])

In [25]:
result = (5 * x) + (3 * x)
result

array([[32, 24]])

In [26]:
result = 8 * x
result

array([[32, 24]])

In [27]:
result = (4 * x) - x
result

array([[12,  9]])

In [28]:
x.T.shape

(2, 1)

In [29]:
if x.shape == x.T.shape:
    print(x + x.T)
else:
    print('Not defined')

Not defined


In [30]:
from numpy import linalg as LA
LA.norm(x)

5.0

10.1.2 <br/>
Definiera vektorn

In [31]:
v = np.array([[3], [7], [0], [11]])
print(v)
v.shape

[[ 3]
 [ 7]
 [ 0]
 [11]]


(4, 1)

In [66]:
2 * v

array([[ 6],
       [14],
       [ 0],
       [22]])

In [67]:
(5 * v) + (2 * v)

array([[21],
       [49],
       [ 0],
       [77]])

In [68]:
(4 * v) - (2 * v)

array([[ 6],
       [14],
       [ 0],
       [22]])

In [35]:
v.T.shape

(1, 4)

In [36]:
LA.norm(v)

13.379088160259652

10.1.3<br/>
Definiera vektorerna V1 = (4, 3, 1, 5) och V2 = (2, 3, 1, 1).

In [37]:
v1 = np.array([[4, 3, 1, 5]])
LA.norm(v1)

7.14142842854285

In [65]:
v2 = np.array([[2, 3, 1, 1]])
LA.norm(v2)

3.872983346207417

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

10.2.1<br/>
Definiera matriserna:

In [40]:
A = np.array([[2, 1, -1], 
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4, -2]])

C = np.array([[1, 2],
      [2,1]])

D = np.array([[3, 4], 
              [4, 3]])

E = np.array([[1], 
              [2]])

I = np.array([[1, 0],
              [0, 1]])

In [44]:
2 * A


array([[ 4,  2, -2],
       [ 2, -2,  2]])

In [45]:
B - (2 * A)

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [47]:
if C.shape == E.shape:
    print((3 @ C) - (2 @ E))
else:
    print('Not defined')

Not defined


In [46]:
(2 * D) - (3 * C)

array([[3, 2],
       [2, 3]])

In [48]:
DD = 2 * D
D.T + DD

array([[ 9, 12],
       [12,  9]])

In [49]:
C.T
(2 * C) - (2 * D)

array([[-4, -4],
       [-4, -4]])

In [50]:
if A.T.shape == B.shape:
    print(A - B)
else:
    print('Not defined')

Not defined


In [51]:
if A.shape == C.shape:
    print(A @ C)
else:
    print('Not defined')

Not defined


In [52]:
C @ D

array([[11, 10],
       [10, 11]])

In [53]:
C @ B

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

In [54]:
C @ I

array([[1, 2],
       [2, 1]])

In [55]:
A @ B.T

array([[5, 2],
       [7, 4]])

10.2.2<br/>
Definiera matrisen 

In [56]:
A = np.array([[2, 3, 4], 
              [5, 4, 1]])

A @ A.T

array([[29, 26],
       [26, 42]])

10.2.3<br/>
Definiera matriserna

In [57]:
A = np.array([[1, 2],
              [2, 4]])

B = np.array([[2, 1],
              [1, 3]])

C = np.array([[4, 3],
              [0, 2]])


In [58]:
# AB = AC
print(A @ B)
print(A @ C)

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [59]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [60]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [61]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
